version: '2'
services:
  nicehash-cryptonight:
    image: crzidea/nicehash-cryptonight
    environment:
      - NICEHASH_WORKER=${DOCKER_HOSTNAME}
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: 262144
    volumes:
      - ./etc/nicehash-cryptonight:/etc/nicehash-cryptonight
    restart: always
